# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-07-19 13:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/')),
                ('title', models.CharField(max_length=60)),
                ('description', models.CharField(blank=True, max_length=300)),
                ('post_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
